### ISSUE TITLE
Runtime Health mode

### ISSUE THREAD

**Issue by lgmu** [ConSol/check_vsphere#1]
Mode in the old plugin: check_vmware_esx -S runtime -s health

Example output: 

OK: All 93 health checks are GREEN: fan (13x), processor (3x), CPU (5x), battery (1x), voltage (4x), systemBoard (1x), memory (1x), other (1x), Memory (5x), Storage (10x), power (10x), temperature (39x) 

WARNING: 1 health issue(s) found in 78 checks: 1) [Warning] [Type: battery] [Name: Battery 1 Megacell Status] [Label: Yellow] [Summary: Sensor is operating under conditions that are non-critical] 

CRITICAL: 1 health issue(s) found in 110 checks: 1) [Critical] [Type: Storage] [Name: Disk or Disk Bay 0 HDD1_STATUS: Drive Fault - Assert] [Label: Red] [Summary: Sensor is operating under critical conditions]

**Comment by datamuc** [comment]
implemented

https://consol.github.io/check_vsphere/#/cmd/host-runtime
